services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      MONGO_HOST: mongodb 
      MONGO_PORT: 27017
      MONGO_USER: ${MONGO_USER:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-admin}
      MONGO_DATABASE: ${MONGO_DATABASE:-aseguradora}
      MONGO_REPLICA_SET: ${MONGO_REPLICA_SET:-rs0}

      NEO4J_HOST: neo4j
      NEO4J_BOLT_PORT: 7687 
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-neoadmin}
    volumes:
      - ..:/app
      - /app/node_modules
    networks:
      - db_network
    command: tail -f /dev/null
    depends_on:
      - mongodb
      - neo4j
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-admin}
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--auth"]
    networks:
      - db_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neoadmin}
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    networks:
      - db_network
      

volumes:
  mongodb_data:
  neo4j_data:
  neo4j_plugins:

networks:
  db_network:
    driver: bridge
